In [1]:
from numpy import random

In [4]:
print(random.randint(1,100))
print(random.rand())

96
0.1703982312607356


In [5]:
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))



[ 7 66 29]
[[24  8 82  5]
 [ 6  5 35 64]
 [75 52 11 44]]
[[[39 15]
  [31 93]
  [27 59]
  [42 69]]

 [[18  3]
  [45 65]
  [ 2 73]
  [52 72]]

 [[35 82]
  [30 10]
  [97 17]
  [36 27]]]


In [6]:
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.5671620655306847
[0.79657971 0.71526896 0.31065362]
[[0.60401684 0.95492605 0.88423339]
 [0.64779826 0.83603779 0.57680379]]


In [7]:
a=random.randint(100,size=(3,2)).ravel()
a

array([73, 24, 91,  2, 84, 43])

In [8]:
random.choice(a)# single element will be selected

73

In [10]:
random.choice([1,2,3,4],size=(4,4))#for generating array of given size and elements from the list

array([[1, 1, 1, 3],
       [1, 3, 3, 3],
       [2, 3, 3, 4],
       [1, 2, 3, 4]])

# pandas:
1. data manupulation,analysis,and cleaning
2. data used: tabular data,unlabled data,orderd or unordered
3. rows=index and columns=headers
4. data frame is collection of rows and columns
5. series=represents one column value in data frame

# creating a data frame
1. Create DataFrame with two dictionaries
2. We can also create simply by creating a dictionary and converting it directly to a DataFrame.
3. Create DataFrame with Series
4. DataFrame can also be created by using the CSV File


In [14]:
#Create DataFrame with two dictionaries
import pandas as pd
import numpy as np
dict1={'a':1,'b':2,'c':3,'d':4,'e':5}
dict2={'a':5,'b':6,'c':7,'d':8,'e':9}
data={'first':dict1,'second':dict2}
df=pd.DataFrame(data,dtype=np.int32)
df

first  second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [13]:
import pandas as pd
import numpy as np
dict1={'a':1,'b':2,'c':3,'d':4,'e':5}
dict2={'a':5,'b':6,'c':7,'d':8,'f':9}
data={'first':dict1,'second':dict2}
df=pd.DataFrame(data)
df#NaN=not a number 

first  second
a    1.0     5.0
b    2.0     6.0
c    3.0     7.0
d    4.0     8.0
e    5.0     NaN
f    NaN     9.0

In [17]:
# We can also create simply by creating a dictionary and converting it directly to a DataFrame.
# simpl dictonary----->data frame
d1={'name':["abc","xyz"],'address':["hyd","chennai"]}
df1=pd.DataFrame(d1)
df1

name  address
0  abc      hyd
1  xyz  chennai

In [21]:
#Create DataFrame with Series
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s2=pd.Series([1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,1.10])
s3=pd.Series(["a","b","c","d","e","f","g","h","i","j"])
dic={"col1":s1,"col2":s2,"col3":s3}
df3=pd.DataFrame(dic)
df3

col1  col2 col3
0     1   1.1    a
1     2   1.2    b
2     3   1.3    c
3     4   1.4    d
4     5   1.5    e
5     6   1.6    f
6     7   1.7    g
7     8   1.8    h
8     9   1.9    i
9    10   1.1    j

# selecting the data from data frame
1. loc ```variable.loc["row","coloumn"]``` -use labels  
2. iloc- use positions

In [22]:
df3["col2"]#selcting single column data

0    1.1
1    1.2
2    1.3
3    1.4
4    1.5
5    1.6
6    1.7
7    1.8
8    1.9
9    1.1
Name: col2, dtype: float64

In [24]:
df3[["col1","col2"]]#selcting multiple columns data

col1  col2
0     1   1.1
1     2   1.2
2     3   1.3
3     4   1.4
4     5   1.5
5     6   1.6
6     7   1.7
7     8   1.8
8     9   1.9
9    10   1.1

In [26]:
df3.loc[:,"col1"]# : -------->indicates all the rows

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: col1, dtype: int64

In [29]:
df3.loc[:,:]

col1  col2 col3
0     1   1.1    a
1     2   1.2    b
2     3   1.3    c
3     4   1.4    d
4     5   1.5    e
5     6   1.6    f
6     7   1.7    g
7     8   1.8    h
8     9   1.9    i
9    10   1.1    j

In [30]:
df3.loc[0:5,["col1","col2"]]

col1  col2
0     1   1.1
1     2   1.2
2     3   1.3
3     4   1.4
4     5   1.5
5     6   1.6

In [35]:
df3.iloc[0:4,0:1]

col1
0     1
1     2
2     3
3     4

In [36]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: col1, dtype: int64

# retreving information from data frame

In [37]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    10 non-null     int64  
 1   col2    10 non-null     float64
 2   col3    10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [39]:
df3.shape

(10, 3)

In [40]:
df3.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [41]:
df3.index

RangeIndex(start=0, stop=10, step=1)

# viewing the data from dataframe
1. head()-return first five rows from dataframe by default
2. tail()-returns last five values of thedataframe
3. sample()-selects random values

In [48]:
df3.head()

col1  col2 col3
0     1   1.1    a
1     2   1.2    b
2     3   1.3    c
3     4   1.4    d
4     5   1.5    e

In [47]:
df3.head(3)

col1  col2 col3
0     1   1.1    a
1     2   1.2    b
2     3   1.3    c

In [46]:
df3.tail()

col1  col2 col3
5     6   1.6    f
6     7   1.7    g
7     8   1.8    h
8     9   1.9    i
9    10   1.1    j

In [52]:
df3.sample()

col1  col2 col3
0     1   1.1    a

In [53]:
df3.sample(2)

col1  col2 col3
1     2   1.2    b
9    10   1.1    j

In [54]:
df3.tail(3)

col1  col2 col3
7     8   1.8    h
8     9   1.9    i
9    10   1.1    j

In [55]:
df3.describe()

col1       col2
count  10.00000  10.000000
mean    5.50000   1.460000
std     3.02765   0.287518
min     1.00000   1.100000
25%     3.25000   1.225000
50%     5.50000   1.450000
75%     7.75000   1.675000
max    10.00000   1.900000

In [59]:
a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])

c=np.append(a,b,axis=1)

print(c)

[[ 1  2  3 11 21 31]
 [ 4  5  6 42 52 62]
 [ 7  8  9 73 83 93]]
